 
module.sw.eshipment.gcf.url=$[sw.eshipment.gcf_URL]
module.sw.eshipment.gcf.user=$[sw.eshipment.gcf_User]
module.sw.eshipment.gcf.password=$[sw.eshipment.gcf_Password]
module.sw.eshipment.gcf.tables.ied=IEDsw_eshipment
module.sw.eshipment.gcf.tables.history=Historysw_eshipment
module.sw.eshipment.gcf.tables.locks=Lockssw_eshipment
module.sw.eshipment.gcf.tables.track=Tracksw_eshipment


