#
#    **************************************************************************
#    * @ProjectName_____________________________________@    Version: @VerNr@ *
#    *                                                                        *
#    * This software is the proprietary information of STRATEGY OBJECT.       *
#    * Use is subject to license terms.                                       *
#    *                                                                        *
#    * Copyright (c) 1997-2009 STRATEGY OBJECT                                *
#    * All rights reserved.                           @VersionDate__________@ *
#    **************************************************************************

# Sample ResourceBundle properties file

# The
module.name=sw.swtraining
module.release=1
module.fullname=swtraining
module.version=1.0
module.type=Application Modules
module.basename=${module.name}/${module.release}
module.license=FREE
module.summary=Basic for Taining
module.description=Basic for Training
