#Default skin configuration
SkinName=awskin 

#-------> All options below will be used only if the coresponding option inside
#-------> server/etc/config/client.properties does not exist! The server administrator will be always able
#-------> to override these options by uncommenting the corresponding lines in client.properites.

ApplicationName=Rwanda e-Single Window (4.3.2 Prod)
ApplicationVersion=4.3.2

# ------->  The title of client.
# ------->   {0} - it is property ClientApplicationName
# ------->  {1} - the user name.

Title={0} - {1}

# -------> if you don't want these icons to be resized, please comment the lines below. It will also increase the
# -------> performance - the desktop will be loaded faster
IconSizeToolbar=28
#IconSizeMenuAbout=32
IconSizeMenuItem=20

# -------> Even if the resizing is allowed, do not resize toolbar/menu item icons, if their 
# -------> size is similar (10% maximum difference allowed). Strongly recommended!
DoNotResizeSimilarIcons=true

# --------> Even if the resizing of menu items is allowed, do not resize the document library menu!
# --------> Strongly recommended - the desktop will begin to load faster
DoNotResizeDocumentLibraryMenu=true

# -------> My Profile document - size of the automatically generated icon 
IconSizeMyProfile=48
#DesktopFactory=un.kernel.client.desktop.factories.AsycudaDesktopFactory
#DesktopFactory=un.kernel.client.desktop.factories.DockableDesktopFactory
LAFManager.UseInstalled=no
LAFManager.Default=so.kernel.client.skin.AWMetalLookAndFeel
LAFManager.ToInstallLAFs=so.kernel.client.skin.AWMetalLookAndFeel
#LAFManager.Plugin=so.kernel.client.skin.AWMetalLookAndFeel
#PageTabsBackground=#00A1DE;
#PageTabsForeground=#000000;