
@include sw.swtraining.registry.trader.properties
module.sw.swtraining.gcf.url=$[sw.swtraining.gcf_URL]
module.sw.swtraining.gcf.user=$[sw.swtraining.gcf_User]
module.sw.swtraining.gcf.password=$[sw.swtraining.gcf_Password]
module.sw.swtraining.gcf.tables.ied=SW_SWTRAINING_IED
module.sw.swtraining.gcf.tables.history=SW_SWTRAINING_HISTORY
module.sw.swtraining.gcf.tables.locks=SW_SWTRAINING_LOCKS
module.sw.swtraining.gcf.tables.track=SW_SWTRAINING_TRACK
# Multimedia storage tables
module.sw.swtraining.media.tables.url=$[sw.swtraining.Multimediainfo_URL]
module.sw.swtraining.media.tables.user=$[sw.swtraining.Multimediainfo_User]
module.sw.swtraining.media.tables.pass=$[sw.swtraining.Multimediainfo_Password]
module.sw.swtraining.media.tables.id.generator=sw_swtraining_IDGenerator
module.sw.swtraining.media.tables.resources.details=sw_swtraining_ResDetails
module.sw.swtraining.media.tables.multimedia=sw_swtraining_Multimedia
module.sw.swtraining.media.tables.multimedia.resources=sw_swtraining_MultimediaRes
module.sw.swtraining.content.datas.table=sw_swtraining_ContentDatas



