-- E-Shipment table creation script
-- Run as: sqlplus SOADM/<password>@localhost:1521/xepdb1 @create_tables.sql

CREATE TABLE SHIPMENT_TRANSFER_NOTES (
    INSTANCEID      NUMBER          NOT NULL,
    SHP_REF_NBR     VARCHAR2(30),
    SHP_TRD_TIN     VARCHAR2(15),
    SHP_PLT_NBR     VARCHAR2(15),
    SHP_DRV_NAM     VARCHAR2(100),
    SHP_SEL_NBR     VARCHAR2(20),
    SHP_WH_SOURCE   VARCHAR2(10),
    SHP_WH_TARGET   VARCHAR2(10),
    SHP_DEP_DATE    TIMESTAMP,
    SHP_ARV_DATE    TIMESTAMP,
    SHP_STATUS      VARCHAR2(20),
    CONSTRAINT PK_SHIPMENT_TRANSFER PRIMARY KEY (INSTANCEID)
);

CREATE INDEX IDX_SHP_REF    ON SHIPMENT_TRANSFER_NOTES (SHP_REF_NBR);
CREATE INDEX IDX_SHP_WH_FROM ON SHIPMENT_TRANSFER_NOTES (SHP_WH_SOURCE);
CREATE INDEX IDX_SHP_PLT    ON SHIPMENT_TRANSFER_NOTES (SHP_PLT_NBR);

CREATE TABLE SHIPMENT_CARGO_ITEMS (
    INSTANCEID  NUMBER      NOT NULL,
    KEY_RNK     NUMBER      NOT NULL,
    HS_CODE     VARCHAR2(12),
    PKG_COUNT   NUMBER,
    CONSTRAINT PK_SHIPMENT_CARGO PRIMARY KEY (INSTANCEID, KEY_RNK)
);

COMMIT;
EXIT;
