#
#    **************************************************************************
#    * @ProjectName_____________________________________@    Version: @VerNr@ *
#    *                                                                        *
#    * This software is the proprietary information of STRATEGY OBJECT.       *
#    * Use is subject to license terms.                                       *
#    *                                                                        *
#    * Copyright (c) 1997-2009 STRATEGY OBJECT                                *
#    * All rights reserved.                           @VersionDate__________@ *
#    **************************************************************************

# Sample ResourceBundle properties file

# The
module.name=sw.eshipment
module.release=1
module.fullname=eshipment
module.version=1.0
module.type=Application Modules
module.basename=${module.name}/${module.release}
module.license=N/A
module.summary=Tracking Document 
module.description=A document to trach goods moving between warehouses before they reach the final export stage
